### ISSUE TITLE
Add pygmentize to use minted to latex:full

### ISSUE THREAD

**Issue by alexpacini** [Dockershelf/dockershelf#33]
To use minted it requires pygmentize, but this is missing from the full image.
```
apt install python3-pygments
```

**Comment by LuisAlejandro** [comment]
@alexpacini Sure thing, it will be included on the next release.

Thanks for reporting.

**Comment by alexpacini** [comment]
Sorry, the name is pygments (not pygmentize).

**Comment by LuisAlejandro** [comment]
Hi @alexpacini, python3-pygments has been included in the new release. Check if it suits your needs, feel free to report any errors or suggestions.
